import React, { useEffect, useState } from 'react';
import { Layout, PageHero } from '../components';

export default function Contact(){
  const [form,setForm]=useState({name:'',email:'',company:'',message:''});
  const [error,setError]=useState('');
  useEffect(()=>{const saved=localStorage.getItem('grantxpertFinderProfile');if(saved){try{const p=JSON.parse(saved);setForm(v=>({...v,message:`I used the preliminary Funding Finder.\nOrganisation: ${p.org}\nFocus: ${p.focus}\nGoal: ${p.goal}\nProject idea: ${p.idea||'Not provided'}\n\nI would like to discuss suitable active funding opportunities.`}));}catch{}}},[]);
  const onChange=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
  const submit=e=>{e.preventDefault();if(!form.name.trim()||!form.email.trim()||!form.message.trim()){setError('Please complete your name, email and message.');return;}setError('');const subject=encodeURIComponent(`Funding enquiry from ${form.name}${form.company?' — '+form.company:''}`);const body=encodeURIComponent(`Name: ${form.name}\nEmail: ${form.email}\nOrganisation: ${form.company||'Not provided'}\n\n${form.message}`);window.location.href=`mailto:admin@grantxpert.eu?subject=${subject}&body=${body}`;};
  return <Layout page="contact"><PageHero eyebrow="Contact" title="Bring the project idea. Start with the right questions." text="Use the form to prepare an email to GrantXpert, or contact the team directly by phone or email." image="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1500&q=82"/>
    <section className="section"><div className="shell contact-layout"><form className="contact-form" onSubmit={submit}><span className="eyebrow">Project enquiry</span><h2>Tell GrantXpert what you are trying to achieve.</h2><div className="two-fields"><label>Name<input name="name" value={form.name} onChange={onChange} placeholder="Your name"/></label><label>Email<input name="email" type="email" value={form.email} onChange={onChange} placeholder="you@example.com"/></label></div><label>Organisation<input name="company" value={form.company} onChange={onChange} placeholder="Company / university / NGO"/></label><label>Message<textarea name="message" rows="8" value={form.message} onChange={onChange} placeholder="Tell us about your project idea..."/></label>{error&&<div className="form-error" style={{display:'block'}}>{error}</div>}<button className="btn" type="submit">Prepare email →</button><small>This concept opens your default email app so the enquiry is not silently stored or faked.</small></form>
      <div className="contact-cards"><div className="contact-card"><div className="service-icon">PH</div><div><span>Phone</span><a href="tel:+35722669266">+357 22 669266</a></div></div><div className="contact-card"><div className="service-icon">EM</div><div><span>Email</span><a href="mailto:admin@grantxpert.eu">admin@grantxpert.eu</a></div></div><div className="contact-card"><div className="service-icon">CY</div><div><span>Office</span><p>47 28th October Avenue<br/>Office 302, 2414, Engomi<br/>Nicosia, Cyprus</p></div></div><div className="contact-card"><div className="service-icon">WEB</div><div><span>Official website</span><a href="https://www.grantxpert.eu/" target="_blank" rel="noreferrer">www.grantxpert.eu ↗</a></div></div></div>
    </div></section></Layout>;
}
