import React, { useState } from 'react';
import { Layout, PageHero } from '../components';

const programs=[
  {name:'Horizon Europe',icon:'RI',tags:['research','innovation','ai','health','green','university','research institute','sme'],summary:'Strong route for ambitious research and innovation projects, often developed through international consortia.',url:'https://research-and-innovation.ec.europa.eu/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe_en'},
  {name:'Erasmus+',icon:'ED',tags:['education','training','skills','youth','university','ngo','school','vet','sme'],summary:'Relevant for education, training, skills, youth, cooperation partnerships and alliances for innovation.',url:'https://erasmus-plus.ec.europa.eu/'},
  {name:'Digital Europe',icon:'DE',tags:['digital','ai','cybersecurity','data','skills','sme','public body','innovation'],summary:'Targets strategic digital capacities and deployment in AI, cybersecurity, data and advanced digital skills.',url:'https://digital-strategy.ec.europa.eu/en/activities/digital-programme'},
  {name:'Creative Europe',icon:'CE',tags:['creative','culture','media','ngo','sme','education'],summary:'A possible route for cultural, creative and audiovisual cooperation and innovation projects.',url:'https://culture.ec.europa.eu/creative-europe'},
  {name:'EIT Opportunities',icon:'EIT',tags:['innovation','startup','entrepreneurship','education','sme','university','green','health','digital'],summary:'Innovation ecosystem opportunities connecting business, education and research around European challenges.',url:'https://eit.europa.eu/our-activities/opportunities'}
];

export default function FundingFinder(){
  const [form,setForm]=useState({org:'',focus:'',goal:'',idea:''});
  const [error,setError]=useState('');
  const [matches,setMatches]=useState([]);
  const onChange=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
  const submit=e=>{e.preventDefault(); if(!form.org||!form.focus||!form.goal){setError('Please select your organisation type, focus area and main goal.');setMatches([]);return;} setError('');
    const corpus=(form.org+' '+form.focus+' '+form.goal+' '+form.idea).toLowerCase().replaceAll('/',' ');
    const ranked=programs.map(p=>{let score=p.tags.reduce((n,t)=>n+(corpus.includes(t)?2:0),0);if(p.name==='Horizon Europe'&&/(research|innovation)/.test(corpus))score+=3;if(p.name==='Erasmus+'&&/(education|training|skills|youth|school|vet)/.test(corpus))score+=3;if(p.name==='Digital Europe'&&/(digital|ai|cyber|data)/.test(corpus))score+=3;if(p.name==='Creative Europe'&&/(culture|creative|media)/.test(corpus))score+=4;if(p.name==='EIT Opportunities'&&/(startup|entrepreneur|innovation)/.test(corpus))score+=3;return {...p,score};}).sort((a,b)=>b.score-a.score).slice(0,3);
    localStorage.setItem('grantxpertFinderProfile',JSON.stringify(form)); setMatches(ranked); setTimeout(()=>document.getElementById('finderResults')?.scrollIntoView({behavior:'smooth',block:'start'}),50);
  };
  return <Layout page="funding-finder"><PageHero eyebrow="Interactive concept" title="Start with your organisation — not a wall of funding links." text="Answer a few questions to generate a preliminary shortlist of EU programme families that may be worth exploring with GrantXpert." image="https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1500&q=82"/>
    <section className="section"><div className="shell finder-layout"><form className="finder-form" onSubmit={submit}><span className="eyebrow">Preliminary match</span><h3>Tell us about your project</h3><p>No login. No funding claim. Just an initial direction.</p>
      <label>Organisation type<select name="org" value={form.org} onChange={onChange}><option value="">Select one</option>{['SME','Startup','University','Research Institute','NGO','School / VET Provider','Public Body / Municipality','Creative / Cultural Organisation'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label>Main focus<select name="focus" value={form.focus} onChange={onChange}><option value="">Select one</option>{['AI / Data / Digital','Education / Training / Skills','Green / Sustainability','Health / Digital Health','Entrepreneurship / Startups','Culture / Creative / Media','Youth / Employability','Research & Innovation'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label>Main goal<select name="goal" value={form.goal} onChange={onChange}><option value="">Select one</option>{['Research & develop','Train / upskill people','Build a partnership','Deploy digital technology','Develop a new service / model','Run a social or community initiative'].map(x=><option key={x}>{x}</option>)}</select></label>
      <label>Project idea <span>(optional)</span><textarea name="idea" rows="5" value={form.idea} onChange={onChange} placeholder="Describe the idea in a few lines..."/></label>
      {error&&<div className="form-error" style={{display:'block'}}>{error}</div>}<button className="btn" type="submit">Generate preliminary matches →</button><small>This tool is an initial orientation only. Final eligibility depends on the live call, consortium, geography, budget and detailed rules.</small>
    </form><aside className="finder-aside"><span className="eyebrow">Why this helps</span><h3>A useful funding conversation starts with context.</h3><p>A programme name alone is not enough. A consultant needs to understand who you are, what you want to achieve and how the project creates European value.</p><div className="check-list"><span>Faster lead qualification</span><span>Better first consultation</span><span>Clearer visitor experience</span><span>No fake funding promise</span></div><a className="text-link" href="contact.html">Prefer to speak directly? →</a></aside></div></section>
    {matches.length>0&&<section id="finderResults" className="section soft results show"><div className="shell"><span className="eyebrow">Preliminary result</span><h2 style={{marginTop:10}}>Your strongest programme routes to investigate</h2><div className="match-grid">{matches.map((p,i)=><article className="match-card" key={p.name}><div className="match-rank">0{i+1}</div><div className="service-icon">{p.icon}</div><span className="fit">{i===0?'Strongest preliminary fit':'Worth exploring'}</span><h3>{p.name}</h3><p>{p.summary}</p><a href={p.url} target="_blank" rel="noreferrer">Official programme page ↗</a></article>)}</div><div className="result-cta"><div><strong>Want a consultant to review the idea?</strong><span>Your finder profile will be carried into the contact form on this device.</span></div><a className="btn" href="contact.html">Discuss these results →</a></div></div></section>}
  </Layout>;
}
