import React from 'react';
import { Layout, CTA } from '../components';
import { services, projects } from '../siteData';

export default function Home(){
  return <Layout page="home">
    <section className="hero"><div className="hero-bg"></div><div className="hero-overlay"></div><div className="shell"><div className="hero-copy"><span className="eyebrow light">EU funding • clearer decisions • stronger projects</span><h1>Turn ambitious ideas into <span>fundable European projects.</span></h1><p>GrantXpert helps organisations navigate funding opportunities, build competitive proposals and manage approved projects with confidence.</p><div className="hero-actions"><a className="btn gold" href="funding-finder.html">Find your funding route →</a><a className="btn ghost" href="projects.html">Explore projects ↗</a></div><div className="trust-line"><span>EU funding expertise</span><span>Proposal & project support</span><span>Training & partnerships</span></div></div><aside className="hero-panel"><span className="kicker">Start with a 2-minute profile</span><h3>Which EU programme could fit your organisation?</h3><p>Use the preliminary Funding Finder to shortlist programmes worth discussing with a consultant.</p><a className="panel-link" href="funding-finder.html">Open Funding Finder <span>→</span></a><div className="stats-mini"><div><strong>160+</strong><span>Approved EU-funded projects*</span></div><div><strong>30+</strong><span>EU programmes*</span></div><div><strong>€10M+</strong><span>Total EU project value*</span></div><div><strong>2009</strong><span>Operating since*</span></div></div><small>*Concept figures based on public GrantXpert information and should be verified before production use.</small></aside></div></section>

    <section className="section"><div className="shell"><span className="eyebrow">A complete funding journey</span><div className="journey-grid">{[['01','Discover','Identify opportunities aligned with your organisation and project idea.'],['02','Prepare','Shape the concept, consortium, proposal and supporting documentation.'],['03','Deliver','Manage financial, administrative and implementation requirements.'],['04','Grow','Build skills, partnerships and future funding capacity.']].map(x=><div className="journey" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>

    <section className="section soft"><div className="shell split"><div className="image-box"><img src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1500&q=82" alt="Strategy workshop"/><div className="float-card"><span className="icon">EU</span><div><strong>From complexity to clarity</strong><span>A decision path instead of a link list</span></div></div></div><div className="copy"><span className="eyebrow">A smarter first step</span><h2>Funding information is everywhere. The challenge is knowing what matters to you.</h2><p className="lead">This concept upgrades the usual EU Calls experience into a guided route: profile the organisation, identify likely programmes, understand why they may fit, then move to a real consultation.</p><div className="check-list"><span>Organisation-based matching</span><span>Topic and objective scoring</span><span>Direct links to official EU programme pages</span><span>Clear handoff to GrantXpert consultation</span></div><a className="text-link" href="funding-finder.html">Try the Funding Finder →</a></div></div></section>

    <section className="section"><div className="shell"><div className="section-head"><div><span className="eyebrow">What GrantXpert supports</span><h2>One partner across the project cycle.</h2></div><a className="text-link" href="services.html">All services →</a></div><div className="service-grid">{services.map(s=><article className="service-card" key={s.title}><span className="service-icon">{s.icon}</span><h3>{s.title}</h3><p>{s.text}</p><a href={s.title==='Training'?'training.html':'contact.html'}>Discuss this service →</a></article>)}</div></div></section>

    <section className="section dark-section"><div className="shell"><div className="section-head light"><div><span className="eyebrow light">Selected work</span><h2>European projects across digital, skills, sustainability and innovation.</h2></div><a className="btn ghost" href="projects.html">View project portfolio →</a></div><div className="project-grid">{projects.slice(0,3).map(p=><article className="project-card" key={p.title}><div className="project-top"><span>{p.programme}</span><span>↗</span></div><h3>{p.title}</h3><div className="project-meta"><span className="pill">{p.years}</span><span className="pill">{p.category}</span></div><p>{p.text}</p><a href="https://www.grantxpert.eu/our-projects" target="_blank" rel="noreferrer">Official portfolio ↗</a></article>)}</div></div></section>
    <CTA/>
  </Layout>;
}
